<?php

namespace FamilyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FatherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FatherRepository extends EntityRepository
{
}
